# Generated by Django 5.1.1 on 2024-09-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
